### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by JABClari** [CodyHouse/codyhouse-framework#10]
The **_grid_** class applies **_padding_** which gives a weird result. I don't know the notion behind it. Check it out in the image below.
`<div class='grid'>`

Computed Result
 ###### padding : var(--space-md) 0 0 var(--space-md); 
*padding-top: var(--space-md);
*padding-right: 0;
*padding-bottom: 0;
*padding-left: var(--space-md);

What's the reason behind the 0 0 on the right and bottom ?
![screenshot 323](https://user-images.githubusercontent.com/7349938/52998498-549f5400-341b-11e9-8839-ca6f9c415844.png)

**Comment by sebastiano-guerriero** [comment]
The padding values applied to the grid elements are used to set the grid gap (you can overwrite it using one of the .grid-gap-- classes). They work in combo with the negative margins applied to the grid container (which make sure the grid is aligned with other layout elements). If you want to style a grid item, I'd suggest to create a new element inside the .col-- element (and use the grid classes only for setting layout rules). Cheers

**Comment by sebastiano-guerriero** [comment]
Docs page about grid & layout:
https://codyhouse.co/ds/docs/globals/grid-layout
