### ISSUE TITLE
aspect-ratio in v3 not working properly

### ISSUE THREAD

**Issue by starchild** [CodyHouse/codyhouse-framework#102]
Hi,

it seems the object-fit is not working correctly.  It was fine with v1.

I don't think I'm doing it wrong?

&lt;div class=&quot;grid gap-xs&quot;&gt;
&lt;div class=&quot;col-3@md col-3@sm flex&quot;&gt;
&lt;figure class=&quot;aspect-ratio-1:1 width-100%&quot;&gt;
&lt;a data-fancybox=&quot;photo-gallery&quot; href=&quot;/url&quot;&gt;
&lt;picture&gt;
&lt;source srcset=&quot;/imagename.jpg.webp 1x&quot; type=&quot;image/webp&quot;&gt;
&lt;source srcset=&quot;/imagename.jpg 1x&quot; type=&quot;image/jpeg&quot;&gt;
&lt;img src=&quot;/imagename.jpg&quot; loading=&quot;lazy&quot; id=&quot;name&quot; data-src=&quot;/imagename.jpg&quot;&gt;
&lt;/picture&gt;
&lt;/a&gt;
&lt;/figure&gt;
&lt;/div&gt;
&lt;/div&gt;

Thank you.

**Comment by claudia-romano** [comment]
Hi there, you should give the `aspect-ratio` class to the image parent, in your example the `<picture>` element.

**Comment by starchild** [comment]
Unfortunately this still doesn't work.  I even tried moving the flex class to the figure element.

**Comment by starchild** [comment]
Thank you Claudia, I finally got this working with that and also moving the flex class to the a tag.  You guys are great :)
