### ISSUE TITLE
Base css being compiled 15 times into style.css!

### ISSUE THREAD

**Issue by starchild** [CodyHouse/codyhouse-framework#107]
For some reason, when gulp is compiling, I'm seeing what looks liek the base css in the file around 15 times.  

The file is nearly 4mb!!

These are the contents of style.scss

@use 'base' with (
  $breakpoints: (
    'xs': 32rem, // ~512px
    'sm': 48rem, // ~768px
    'md': 64rem, // ~1024px
    'lg': 80rem, // ~1280px
    'xl': 90rem  // ~1440px
  ),
  $grid-columns: 12
);

/*! purgecss start ignore */
@use 'custom-style';
@use 'components/**/*.scss';
@use 'custom-components';

/*! purgecss end ignore */

@import 'box';
@import 'base';
@import 'custom-style';
@import 'components';
@import 'custom-components';
@import 'cartt';
@import 'font-awesome';
@import 'usernoise';
@import 'simple_menu';
@import 'owl';
@import 'navigation';

What am I doing wrong please?

**Comment by sebastiano-guerriero** [comment]
more info here: https://sass-lang.com/documentation/at-rules/use

**Comment by starchild** [comment]
Thank you.  I've moved to 2.91 and things seem much better now.
