### ISSUE TITLE
Alias Colour Properties to meaningful scoped component names

### ISSUE THREAD

**Issue by aaronstezycki** [CodyHouse/codyhouse-framework#108]
Hi all.

I came across the [article](https://codyhouse.co/blog/post/how-to-combine-sass-color-functions-and-css-variables) about using custom properties for colour definitions/tokens which I found very helpful. Being able to change alpha/saturation whilst still using colours from the global colour palette is handy.

One thing I and team have found the technique falls short on, is being able to alias colour tokens to more defined roles so that naming is less abiguious and more specific. Being able to do the following would make more sense to some of our developers that are learning the code base and the design system.

```
:root {
  --input-text-color: var(--slate-600); // this works
  --input-ring: var(--blue-600); // this works
  --input-outline: alpha(var(--blue-600)); // this doesnt work.
}

.input {
  color: var(--input-text-color);
  border: var(--input-ring);
  box-shadow: var(--input-outline);
}

```

This promotes following guidelines set by design systems and not putting in arbitrary colour tokens into components that can be and are often incorrect. So far, I haven't been able to find a way to getting around effectively using alpha/saturation SASS functions mentioned in the article, because SASS doesn't seem to compile the functions when they are written into the custom properties like so ...

```
:root {
  --input-text-color: alpha(var(--slate-600), 0.5);
}

// Compiles to:
// color: alpha(var(--slate-600), 0.5); 

```

Is there any way around this?

**Comment by sebastiano-guerriero** [comment]
So far I've never experienced any performance issues related to the CSS custom properties. I don't work on websites with millions of daily users (although I inspected Twitter's code and they use CSS custom properties). There are a few interesting article on the topic ((example)[https://lisilinhart.info/posts/css-variables-performance/}). I'd avoid using varibles that target all elements, something like:

```html
* {
  --variable: 20px;
}
```

Hope this helps!

**Comment by aaronstezycki** [comment]
Thanks @sebastiano-guerriero. I've recently too found/inspected multiple websites that use custom properties and in no way a small amount of them. Inspecting Github, they use ~500 custom properties! Thanks for your input.
