### ISSUE TITLE
CodyHouse Pro Twitter link

### ISSUE THREAD

**Issue by astrit** [CodyHouse/codyhouse-framework#111]
Nothing serious here just in case you want to change it. 
https://codyhouse.co/codyhouse-pro
Both twitter links send to Claudia's account 
![image](https://user-images.githubusercontent.com/2398447/141793644-a412b7d1-9bc2-417d-8b70-0fd2716cb0af.png)

**Comment by sebastiano-guerriero** [comment]
Thanks for the heads-up! 👍
