### ISSUE TITLE
Gulp not refreshing Browser But compiles changes

### ISSUE THREAD

**Issue by helphop** [CodyHouse/codyhouse-framework#115]
I have loaded the CodyHouse framework from npm.

I have not made any changes to the gulp file.

I use VS code as my text/code editor VERSION 1.63.2

I am using Firefox 96.02

I have added a component under the components folder in my application.  I can see that any changes I make to the scss are being detected by Gulp.  I can manually reload the webpage and the changes I have made in the scss files are reflected.

However, I have to manually reload the browser, it is not getting the signal to reload from the application for some reason.

Here is the output from the terminal after starting the gulp sever using npm run gulp watch:

```
> codyframe-gulp-starter-template@0.0.4 gulp
> gulp "watch"

[14:41:59] Using gulpfile ~/Desktop/Codyhouse Test/codyframe-gulp-starter-template/gulpfile.js
[14:41:59] Starting 'watch'...
[14:41:59] Starting 'browserSync'...
[14:41:59] Starting '<anonymous>'...
[14:41:59] Finished '<anonymous>' after 8.34 ms
[14:41:59] Finished 'browserSync' after 9.22 ms
[14:41:59] Starting 'sass'...
[Browsersync] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.0.81:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 -------------------------------------
[Browsersync] Serving files from: main
[Browsersync] 1 file changed (style.min.css)
[14:42:00] Finished 'sass' after 1.04 s
[14:42:00] Starting 'scripts'...
[Browsersync] 1 file changed (scripts.js)
[Browsersync] 1 file changed (scripts.min.js)
[14:42:00] Finished 'scripts' after 150 ms
[14:42:00] Starting '<anonymous>'...
[Browsersync] Reloading Browsers... (buffered 3 events)
[14:42:41] Starting 'sass'...
[Browsersync] 1 file changed (style.min.css)
[14:42:42] Finished 'sass' after 619 ms

```

Any assistance to get live reloading working very much appreciated.

**Comment by claudia-romano** [comment]
Hi there,
sorry about the issue. We just pushed an updated version of the gulp starter template that should fix the problem:
https://github.com/CodyHouse/codyframe-gulp-starter-template

You can use the updated 'sass' task:
https://github.com/CodyHouse/codyframe-gulp-starter-template/blob/main/gulpfile.js

I'm closing this issue. If you are still having problems, feel free to reopen it. Thanks!

**Comment by helphop** [comment]
Hey thanks for the quick fix.

Works beautifully. You are awesome.

Best,


Mitchell Gould


On January 26, 2022, Nathan Jones ***@***.***> wrote:
> Hi there,
>  sorry about the issue. We just pushed an updated version of the gulp
> starter template that should fix the problem:
>  <https://github.com/CodyHouse/codyframe-gulp-starter-template>
>
> You can use the updated 'sass' task:
>  <https://github.com/CodyHouse/codyframe-gulp-starter-
> template/blob/main/gulpfile.js>
>
> I'm closing this issue. If you are still having problems, feel free to
> reopen it. Thanks!
>

—
Reply to this email directly, view it on GitHub
<https://github.com/CodyHouse/codyhouse-
framework/issues/115#issuecomment-1021932766>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAFY24ZW5JVMTDYLWJVONBTUX6OPTANCNFSM5MWJTUBA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID:
***@***.***>
