### ISSUE TITLE
how to use it with vite ?

### ISSUE THREAD

**Issue by omarherri** [CodyHouse/codyhouse-framework#124]
Hi i'm trying to migrate from Webpack to [Vite](https://vitejs.dev/guide/) and one of the main issue i found is to merge all components js files into one file. I was wondering if i have to copy paste the content of all the js components in the main file or is there another way to import files ?

**Comment by sebastiano-guerriero** [comment]
Hi Omar, I'm not sure how Vite works, for we've never used it in our projects. Prob a question for the Vite community? 

Cheers

**Comment by omarherri** [comment]
Yeah i do agree. i'm just more a PHP guy and i am not sure if i can use your framework in modular way. 
Like use export & import javascript syntaxes. I ended up switching back to Webpack.
