### ISSUE TITLE
any chance of 10 minutes of zoom support?

### ISSUE THREAD

**Issue by mroswell** [CodyHouse/codyhouse-framework#126]
Doing a lobby day in Washington and would love to use the scheduling template. I need 5 - 10 minutes of support to be able to successfully install the framework and edit the SCSS variables. I'm an experienced web developer on too little sleep and would love it if someone can help me past my current barrier. 

(We have lots of meetings; I need to be able to edit the CSS so that they all display. For whatever reason, I can't figure out where the vars are defined. Maybe I just haven't installed the framework properly; I don't know.)

I'd like to change --schedule-rows-height and some others. 

More

**Comment by claudia-romano** [comment]
Hi there, we do have an Info page that you can check where we provide details on how to customise the component:
https://codyhouse.co/ds/components/info/weekly-schedule

If you are experiencing a specific issue with the component, you can open an issue here:
https://github.com/CodyHouse/cd-weekly-schedule-changelog

Please make sure to provide details of the problem you are facing. Thank you.

I'm closing this as it is not an issue with the framework. Cheers!
