### ISSUE TITLE
Add experiment library to codyhouse components

### ISSUE THREAD

**Issue by CearaWeir** [CodyHouse/codyhouse-framework#128]
The [experiment library](https://codyhouse.co/library) has a lot of good ideas.

Is it possible to add experiment library to codyhouse components ?

**Comment by sebastiano-guerriero** [comment]
Hi! We've already converted quite a few experiments into CodyFrame components and we'll continue to do so. Are you interested into an experiment in particular?

**Comment by CearaWeir** [comment]
OK. Thank you for your work.
