### ISSUE TITLE
Add an option to disable closing a modal by clicking Escape or clicking the backdrop

### ISSUE THREAD

**Issue by lro-tiierisch** [codyhouse/codyhouse-framework#135]
In my opinion you should add an option to disable closing a modal by clicking on its backdrop as well as an option to disable closing a modal by clicking the ESC key.

**Comment by claudia-romano** [comment]
Hi there, thanks for the suggestion. 
ESC key - this has been implemented for keyboard accessibility, so I would suggest not to change it.
As for the backdrop, you should be able to do that by setting a pointer-events none to the .modal element and then setting it to auto for both the .modal__close-btn and the .modal__content element.
