### ISSUE TITLE
Gulp not updating timestamp of css file

### ISSUE THREAD

**Issue by starchild** [CodyHouse/codyhouse-framework#14]
When the new style.css file is created using gulp, the time modified stamp remains untouched.

Ideally we would use this to version the css file but this is not possible without an updated date stamp.

Is this something that can be fixed in gulpfile.js?

**Comment by claudia-romano** [comment]
Hi there, do you have an example of what you mean? Thanks

**Comment by starchild** [comment]
Sure.  I've made a bunch of changes to various _*.scss files, the latest of which was yesterday, and the style.css file gets compiled just fine.

However, the datestamp on the style.scss and style.css files remain at Mar 7.

You can see others talking about this same issue (which seems ot be an issue in gulp 4, but not 3) at https://github.com/gulpjs/gulp/issues/2193 and a possible solution here: https://github.com/dlmanning/gulp-sass/issues/706

**Comment by claudia-romano** [comment]
Hi, thanks for the additional info.
I'm not sure we'll include this fix, as it seems to be an issue with gulp 4 only.
But here's a modified version of the sass task that should fix the issue:
```
var touch = require('gulp-touch-cmd'); // include this module as well
gulp.task('sass', function() {
  return gulp.src('main/assets/css/**/*.scss')
  .pipe(sass({outputStyle: 'expanded'}).on('error', sass.logError))
  .pipe(postcss([autoprefixer(), cssvariables({preserve: true}), calc()]))
  .pipe(gulp.dest('main/assets/css'))
  .pipe(touch())
  .pipe(browserSync.reload({
    stream: true
  }));
});
```
You'll need to install the gulp-touch-cmd module. I've tested it on masOS Mojave and seems to be fixing the issue.

**Comment by starchild** [comment]
Fantastic thanks so much.

I've done this and it works a treat ;)

**Comment by S-n-d** [comment]
Still running into this issue in 2020. Thanks for the tip @claudia-romano !
