### ISSUE TITLE
space in columns width property

### ISSUE THREAD

**Issue by abdulbasetbasher** [CodyHouse/codyhouse-framework#16]
![image](https://user-images.githubusercontent.com/31999439/55235804-0f9ae880-5237-11e9-9d02-d94a6567e808.png)

when I build a style with sacss command I got this in grid system only.

**Comment by sebastiano-guerriero** [comment]
I just checked and it appears we don't have this issue with the Gulp config file of the repo. Are you using our Gulp file or a custom one?

<img width="634" alt="Screenshot 2019-03-29 14 31 58" src="https://user-images.githubusercontent.com/5512742/55239867-761c0880-522f-11e9-992f-2ffb0399b900.png">

**Comment by abdulbasetbasher** [comment]
Solved : when I used Gulp config file of the repo, thank you.
