### ISSUE TITLE
global/_colors: what about --color-info?

### ISSUE THREAD

**Issue by dkipp** [CodyHouse/codyhouse-framework#17]
is the info feedback colors missing?
the currently the there are:
-  error
-  warning
-  sucess

it feels like the info blue is missing.

**Comment by hehehai** [comment]
I think the default color of the codyhouse framework is just a quick start. To add more pre-selected colors to the page, you can use the codyhouse globals color editor to generate the default code and paste it into the `_color.scss` file.

[codyhouse gloabls editor](https://codyhouse.co/ds/globals)
[How to use the Color Editor tool](https://codyhouse.co/ds/docs/globals/colors#color-editor)

**Comment by sebastiano-guerriero** [comment]
Now it's possible to add 'feedback' colors using the color editor https://codyhouse.co/ds/globals/colors
