### ISSUE TITLE
grid gap not working?

### ISSUE THREAD

**Issue by starchild** [CodyHouse/codyhouse-framework#18]
No matter what I try, the grid gap (margin between divs) doesn't work.  I'm testing using the same structure as in the bottom example on https://codyhouse.co/ds/docs/globals/grid-layout

I'm using css from gulp.

Inner padding seems to work, but not margin. (actually, padding on the first div doesn't work, but others are ok)

Am I missing something here?

**Comment by sebastiano-guerriero** [comment]
Can you create a pen on Codepen (or on any other similar service) where you reproduce the issue?

The first thing that comes to mind without a reference: the elements with the grid classes applied should not be 'stylized' (the Grid classes should be used only to create the grid. You can then create additional - inner - elements to set the style of the element - e.g., background-color, border etc...).

**Comment by starchild** [comment]
All I'm doing, is using the default compiled css and the structure below:

<div class="parent grid grid--gap-xs">
    <div class="col--sm-6"></div>
    <div class="col--sm-6"></div>
    <div class="col--md-3"></div>
    <div class="col--md-3"></div>
    <div class="col--md-3"></div>
    <div class="col--md-3"></div>
    <div class="col--lg-2"></div>
    <div class="col--lg-2"></div>
    <div class="col--lg-2"></div>
    <div class="col--lg-2"></div>
    <div class="col--lg-2"></div>
    <div class="col--lg-2"></div>
</div>

This is what's on the demo page.  I see though that on that pen, there is css embedded also - could it be that the css that makes the gaps is not actually in the core repo?

**Comment by starchild** [comment]
I'm going to close this.  When i create the pen it seems ok.  I guess there is something in one of the components possibly that's breaking this for me.  I'll track it down.  Sorry to waste your time.

**Comment by sebastiano-guerriero** [comment]
no prob 👍If you can reproduce the issue on a pen, I'll take a look right away! I'm using the classes on a few components (e.g., https://codyhouse.co/ds/components/app/article-example), and they seem to be working fine.

**Comment by starchild** [comment]
I think I worked this out - I'm trying to apply this to inputs and it doesn't work- divs are ok, but inputs fail. See https://codepen.io/george-costanza/pen/LvovWj

**Comment by sebastiano-guerriero** [comment]
Because the grid utility classes create the gaps using a combination of padding and margins, they should not be used directly on elements that may have padding (e.g., an input element). My suggestion would be to use a separate wrap/container for the grid classes. 

Here's an example where we use the grid classes with input elements:
https://codyhouse.co/ds/components/app/sign-up-form

**Comment by starchild** [comment]
ok, fair enough.
