### ISSUE TITLE
floating label stopped working

### ISSUE THREAD

**Issue by starchild** [CodyHouse/codyhouse-framework#19]
For some reason, when I visit https://codyhouse.co/ds/components/app/floating-label, the component doesn't work.  It was working earlier on.  All browsers are having the issue. (Mac, Mojave)

**Comment by sebastiano-guerriero** [comment]
I just tested on Chrome in an incognito window and it seems to be working fine. Prob a cache issue?

ps: just to be 100% sure, the label floats only after you start typing.

**Comment by starchild** [comment]
Right - the "starts typing" point is a good one to note.

I found one issue, and it has to do with adding the js class to the html tag.  I think instead of 

`<script>document.getElementsByTagName("html")[0].className += "js";</script>`

it needs to be 

`<script>document.getElementsByTagName("html")[0].className += " js";</script>`

note the space before the js - otherwise, if you have any other classes in the html tag, it will append that class instead of adding a new one.

So, now that I've done that, the label hides on load, but the js isn't picking up input text yet so the label is always remaining hidden.  I'm still debugging that bit.

**Comment by claudia-romano** [comment]
Hi, thanks for providing this additional info. 
I double-checked and it looks like the space before the class name was correctly inserted both in the framework (index.html file) and the [documentation page](https://codyhouse.co/ds/docs/framework). 

Is there anywhere else where you found it without the space? So that I can fix the typo (I wasn't able to find it). Thanks.

**Comment by starchild** [comment]
I can't see it for now either.... maybe it was from an original doc file or something.  It was copy/pasted so it must have come from somewhere.  If I find it again I'll . let you know.  Sorry to bother.
