### ISSUE TITLE
text--bold for typography.scss

### ISSUE THREAD

**Issue by w3work** [CodyHouse/codyhouse-framework#22]
Hi Codyhouse-Team,

it would be nice, if you could at a helper class for bold text.
Actually there are only helpers fort text-subtle, text-inherit. But if i want a headline or a span to be bold i only can use the "strong"-tag or make a individual class for them.
I dont want to use the strong tag for bold text, because it is sometimes rendered different in browsers.
So a standard helper class for bold text would be nice.

**Comment by sebastiano-guerriero** [comment]
Hi 👋We've included this helper in the upcoming version ;)

**Comment by w3work** [comment]
Great, thank you! I allready updated to v1.2.0. Is there any schedule, when the globals on the website will be updated to version 1.2.0?

**Comment by claudia-romano** [comment]
Hi! The Globals have now been updated to version 2.0.

**Comment by w3work** [comment]
Sehr geehrte Damen und Herren,

ich bin bis einschließlich 05.07.2019 nicht im Büro erreichbar. 
Ich werde Ihre Anfrage gern nach meiner Rückkehr beantworten. 
Bitte haben Sie Verständnis dafür, dass Ihre E-Mail nicht automatisch weitergeleitet wird.
In dringenden Fällen wenden Sie sich bitte an meine Kollegen im Web-Team unter web@w3work.de

-- 
Viele Grüße

Marcel Fritzsche
w3work - Agentur für Online Marketing
Birkenweg 6
09569 Oederan

Telefon: +49 (0) 3 72 92 / 2882-0
Internet: https://www.w3work.de
