### ISSUE TITLE
Create a design library like https://codyhouse.co/ds/components?

### ISSUE THREAD

**Issue by runnickrun** [CodyHouse/codyhouse-framework#24]
Hey guys, thanks for the great library. 

How do you build and document the actual site, e.g.  https://codyhouse.co/ds/components describing and documenting the design system? Is it open source or you're using something custom? I assume you manage components in some kind of templating language?

Hopefully it makes sense. Thanks in advance.

**Comment by claudia-romano** [comment]
Hi there,
we developed a custom PHP based CMS that we use to create all our pages (components/docs/experiments). It is quite tailored to our needs so we didn't open source it (at least yet). Cheers!

**Comment by runnickrun** [comment]
Thanks for the update!
