### ISSUE TITLE
Layout templates

### ISSUE THREAD

**Issue by kamov** [CodyHouse/codyhouse-framework#25]
First of all congrats for your awesome work!

I found a lot of useful components, and very nice that is all custom built with vanilla JS.

I would like to see some example of layouts, like bootstrap has. Example admin layout with sidebar, etc. Something like:

https://getbootstrap.com/docs/4.3/examples/

**Comment by sebastiano-guerriero** [comment]
Ciao and thanks for the kind words 👋
We'll definitely add more examples in our documentation.

**Comment by kamov** [comment]
Perfetto. Grazie!
