### ISSUE TITLE
Tabs v 2 issue

### ISSUE THREAD

**Issue by starchild** [CodyHouse/codyhouse-framework#27]
on https://codyhouse.co/ds/components/app/tabbed-navigation-v2 the tabs are all pointing to #0 and thus don't open.

**Comment by sebastiano-guerriero** [comment]
The tabbed navigation is a navigation-only component, therefore each link should link (in a production environment) to a different page. To include a tabbed content as well, please refer to the Tabs (https://codyhouse.co/ds/components/app/tabs) component.
