### ISSUE TITLE
How to add letter-spacing to the typography rules?

### ISSUE THREAD

**Issue by JonQuayle** [CodyHouse/codyhouse-framework#28]
Hi,

I've looked through the docs at great length but I can't see how I would add letter-spacing to the typography, specifically, different spacing for each H1, H2, H3 and so on.

Is there a way to do this with the way the typography and responsive sizes work?

Thanks

Jon

**Comment by hehehai** [comment]
https://cssreference.io/property/letter-spacing/#letter-spacing

use `letter-spacing: ?px;`

**Comment by sebastiano-guerriero** [comment]
Hi there 👋
sure thing, you can insert your own typography rules in the custom-style/_typography.scss file of the framework. For example:

```
h1, h2, h3, h4 {
  letter-spacing: 0.1em;
}
<img width="517" alt="Screenshot 2019-06-29 11 01 19" src="https://user-images.githubusercontent.com/5512742/60382022-444c5500-9a5d-11e9-9198-568a59fce677.png">

```

**Comment by JonQuayle** [comment]
Ahh I see, thanks. I thought it might use a css variable to work with the font size and line height. Excellent framework by the way!

Thanks!

**Comment by sebastiano-guerriero** [comment]
no prob! and glad to hear the framework is being useful 😉
