### ISSUE TITLE
Responsive Video Background doesn't play on iPhone

### ISSUE THREAD

**Issue by overstrides** [CodyHouse/codyhouse-framework#29]
https://codyhouse.co/ds/components/app/video-bg

Responsive Video Background doesn't play on iPhone.

I have tested on iPhone 6 plus, iOS 12.3.1
Safari, Chrome, Firefox.

It seems like it needs additional initialization via javascript.

**Comment by claudia-romano** [comment]
Hi there, thanks for the feedback. 
This is an iOS autoplay policy: it is not possible to play a video on your iPhone without the user to willingly activate that video (for example, click on the play button).
I'm not aware of any tricks to force the autoplay. I would not suggest to use it anyway as this would go against the policy (and could easily break with an OS update).

**Comment by illycz** [comment]
Actually I have good experience within autoplaying video on iOS, video must be muted and I'm also using `playsinline` attribute.

**Comment by claudia-romano** [comment]
Perfect! thanks @illycz. 

@overstrides please replace:
```<video autoplay loop muted src="../../assets/video/video-2.mp4">```

with:
```<video autoplay loop muted playsInline src="../../assets/video/video-2.mp4">```

I'll make sure to add the ```playsInline``` attribute to the component as well. Cheers!
