### ISSUE TITLE
Issues with npm install and postcss-css variables

### ISSUE THREAD

**Issue by TadiMercury** [CodyHouse/codyhouse-framework#32]
I've been trying to install the necessary modules for the framework but my computer is running errors. I thought uninstalling everything then reinstalling the files would work but that obviously hasn't worked. I've been struggling with the screenshot below:
![Screenshot (1)](https://user-images.githubusercontent.com/53711492/62480424-1bcc1f00-b7b0-11e9-98ed-5872fff83315.png)

**Comment by claudia-romano** [comment]
Hi @TadiMercury, sorry about that.

It looks like there's an issue while trying to download the node modules. Could you please confirm your device is connected to the internet and you are not on a secure connection that may be blocking the download of the node modules? Thanks.

If the connection is not the issue, could you please try using the npm install command again and, if you get the same error, could you please attach the log file that is created? That could have some additional info about your issue. Thanks.

**Comment by TadiMercury** [comment]
Hi Claudia

My device is connected to the internet and I have done some troubleshooting
myself by using it on a secure and unsecured network. Nothing has changed
however so it seems like internet connection is not the issue.

Please find attached the log file. Thanks for your help.

TadiMercury

**Comment by claudia-romano** [comment]
Hi @TadiMercury, thanks for the info. I didn't get the log file though.
If you have issues attaching it using GitHub, you can send it to help@codyhouse.co. Thanks.

**Comment by TadiMercury** [comment]
Apologies, here it is.
[2019-08-06T17_22_21_018Z-debug.log](https://github.com/CodyHouse/codyhouse-framework/files/3478411/2019-08-06T17_22_21_018Z-debug.log)

**Comment by claudia-romano** [comment]
Hi @TadiMercury thanks for the log file. 

Could you please try running this first:
`npm install CodyHouse/postcss-css-variables --save-dev`

and then:
`npm install`

Do you still get the error? Thanks.

**Comment by TadiMercury** [comment]
Hi,
I still got the same errors when i ran those commands.
Error code:
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/CodyHouse/postcss-css-variables.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

Here's the log file too; Thanks for the help.
[2019-08-08T17_29_11_932Z-debug.log](https://github.com/CodyHouse/codyhouse-framework/files/3482987/2019-08-08T17_29_11_932Z-debug.log)

**Comment by drinkingjava** [comment]
This is a issue I ran into last night. By the looks of it you are running on windows and do not have git installed or the 'git' command is not callable from your from your cmd prompt. After installing https://git-scm.com/ from there type git in a new cmd prompt and if it throws no errors then your npm install should work.

**Comment by TadiMercury** [comment]
Thanks so much, it worked :))
