### ISSUE TITLE
vertical align within a div

### ISSUE THREAD

**Issue by starchild** [CodyHouse/codyhouse-framework#33]
More a question than an issue: In the framework, is there a way to vertically align say an image within a div?  I can't find anything....

**Comment by peiche** [comment]
The easiest way would probably be to use the flex utility classes on the container. Using `flex flex-center` will center vertically and horizontally, while `flex items-center` will only center vertically.

https://codepen.io/peiche/pen/dxdbrJ

**Comment by starchild** [comment]
ty v much, that's just perfect!
