### ISSUE TITLE
single element in carousel

### ISSUE THREAD

**Issue by starchild** [CodyHouse/codyhouse-framework#34]
We have the use case scenario where we only want to show a single item in the carousel.

I've tried setting .carousel__list width to 100%, but when I reduce the width of the page, the image in the list item disappears.

What's the best way to show just a single large item in the carousel at one time?

**Comment by sebastiano-guerriero** [comment]
Hi there! Please refer to the Carousel info page for info about how to customize it:
https://codyhouse.co/ds/components/info/carousel

I'd suggest to take a look at the slideshow component if you want to show a single item:
https://codyhouse.co/ds/components/app/slideshow

**Comment by starchild** [comment]
I did look at the docs but still found no way to do a single image across all view ports - but you're right - simply using the slideshow will solve this.  I didn't think of that.

Thank you.
