### ISSUE TITLE
How to push/pull columns?

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [CodyHouse/codyhouse-framework#37]
Can I push or pull columns like in other frameworks?
Lets say I want to push a 6 col from 3 columns from the left.

In Bootstrap I would use **col-md-offset-3**

    <div class="container max-width-adaptive-lg">
      <div class="grid grid-gap-lg">
        <div class="col-6@md">
          <p>Row 1 column</p>
        </div>
      </div>
    </div>

**Comment by sebastiano-guerriero** [comment]
We don't have offset utility classes, but you can achieve similar results with the help of margin and flexbox utility classes (the .grid class includes display: flex). Do you have a grid example I can look at? (even a screenshot would work)

**Comment by DESIGNfromWITHIN** [comment]
Thank a lot, but its ok was just wondering.
Margin will work fine also.

I am making a MODX CMS + FRED (front end editing for MODX) version of the CodyHouse Framework.
Will share soon I hope.

![cody](https://user-images.githubusercontent.com/725851/63946233-12636900-ca75-11e9-9243-ca1d9839491b.png)

**Comment by sebastiano-guerriero** [comment]
That looks promising! However, please be aware the components are not shared with the same license of the framework and can't be distributed on websites other than codyhouse.co

More info here:
https://codyhouse.co/license

**Comment by DESIGNfromWITHIN** [comment]
Ah damn! I assumed that the basic (none pro) components were ok to use...

Guess Cody is not a option then. Sad to say.
Bootstrap 4 it is then I guess.

Op do 29 aug. 2019 18:15 schreef Sebastiano Guerriero <
notifications@github.com>:

**Comment by sebastiano-guerriero** [comment]
OK! Best of luck :)
