### ISSUE TITLE
grid system not working with style-fallback.css

### ISSUE THREAD

**Issue by smoglica** [CodyHouse/codyhouse-framework#39]
### How to reproduce?

In `index.html`

- add the link tag `<link rel="stylesheet" href="assets/css/style-fallback.css">` and comment the block condition which checks the CSS custom variables support.
- add a simple grid markup (e.g. taken from https://codepen.io/codyhouse/pen/orvKEq) and relative CSS styles.

```html
<div class="parent grid grid-gap-xs">
  <div class="col-1"></div>
  <div class="col-1"></div>
  ...
</div>
```

### What I expect?

After running the dev server (`npm run gulp watch`) the gird system should be identical to that one which supports CSS variables.

But I found out that there are some problems:

- `[class*="grid-gap"]` margins are not applied. Apparently `calc()` it's not able to generate the correct output when a variable in this case `var(--grid-gap)` has also a fallback value (`1em`).

![Screenshot from 2019-09-25 10-25-52](https://user-images.githubusercontent.com/17332096/65587808-beba4180-df86-11e9-9696-ecf3099b7fe3.png)

- `.grid-gap-{size}` will not change the margins of the grid items and also the `[class*="grid-gap"]` will not benefit the changes of the `var(--grid-gap)` from the modifiers.

#### style-fallback.css

When selecting `.grid.grid-gap-xs` element.

![Screenshot from 2019-09-25 11-46-24](https://user-images.githubusercontent.com/17332096/65590060-69802f00-df8a-11e9-9945-4da737c275ee.png)

`.grid-gap-{size}` modifiers are not event generated as class.

#### style.css (supports CSS variables)

When selecting `.grid.grid-gap-xs` element.

![Screenshot from 2019-09-25 11-42-37](https://user-images.githubusercontent.com/17332096/65589703-c0393900-df89-11e9-8028-ebe9589a2dd8.png)

As we can see here the `var(--grid-gap)` it's taken in consideration which reevaluates the size of the gap for the elements which are using it.

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads up. We pushed a new version of the framework (2.1.6) where we fixed the issue with the calc function. It will now set the margin to -1em.

About the --grid-gap variable: IE 11 and below do not support CSS Variables, for this reason, we set the fallback to be 1em for the grid margin (regardless of the grid-gap-* function).

Let me know if you have any questions.

**Comment by smoglica** [comment]
Thank you! So if I understood correctly, in the fallback styles you don't wont do support different gird sizes `.grid-gap--{size}` but keeping always a margin bottom and left of 1em, it's right?

**Comment by claudia-romano** [comment]
Correct! This way, your content on older browsers (like IE11) is still perfectly accessible: you can create your grid and decide whether you need a gap or not. 
On modern browsers (supporting CSS variables), you have the option to customize the gap using the grid-gap-{size} classes.
