### ISSUE TITLE
I can't install npm inside my codyhouse framework directory

### ISSUE THREAD

**Issue by Aaqib33** [CodyHouse/codyhouse-framework#40]
I'm trying hard to install the necessary packages but when I run "npm install" inside the codyhouse-framework directory it gives me a bunch of errors and because of this I also can't run "npm run gulp watch".
I have reinstall the nodejs and check that npm is working fine but it don't work in the framework directory.

Following CMD lines:

E:\CodyHouse\node_modules\codyhouse-framework>npm install
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/CodyHouse/postcss-css-variables.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aqibc\AppData\Roaming\npm-cache\_logs\2019-10-09T07_47_28_158Z-debug.log

Kindly help me out of this!!

**Comment by claudia-romano** [comment]
Hi @Aaqib33,
could you please try installing this first:
https://git-scm.com/

After the installation, please try typing git in a new cmd prompt and if it throws no errors, you should be able to run npm install.

**Comment by Aaqib33** [comment]
> Hi @Aaqib33,
> could you please try installing this first:
> https://git-scm.com/
> 
> After the installation, please try typing git in a new cmd prompt and if it throws no errors, you should be able to run npm install.

Thank you very much @claudia-romano for your help, you made my day. It works 110%.

**Comment by Aaqib33** [comment]
I'm closing this issue.
Thanks again :)
