### ISSUE TITLE
Flash of unstyled page when using JS for CSS fallback

### ISSUE THREAD

**Issue by richardwiggins** [CodyHouse/codyhouse-framework#43]
Hi there, I'm getting a flash of the unstyled page both on local dev and on a live site when using the Javascript css var detection. Basically the css clearly isn't loading quick enough.

If I bypass this and just call the style.css normally the issue disappears. Not a solution really though as I do need the fallback.

Anyone else experienced this or know how to stop the delay?

You can see this on the live site at: https://ligtas.co.uk/

**Comment by w3work** [comment]
You need to update CodyFrame to minimum version 2.2.0. Here they reverted back to document.write() in index.html.

The previous code, like on your site, made this flickering on load/relaod the site. I found this big around a month ago and posted this to the team. So they relased a new bugfixed version.

Here the correct code:
`<script>
    if('CSS' in window && CSS.supports('color', 'var(--color-var)')) {
      document.write('<link rel="stylesheet" href="assets/css/style.css">');
    } else {
      document.write('<link rel="stylesheet" href="assets/css/style-fallback.css">');
    }
  </script>
  <noscript>
    <link rel="stylesheet" href="assets/css/style-fallback.css">
  </noscript>`

**Comment by richardwiggins** [comment]
Awesome, thanks @w3work. That fixed it.
