### ISSUE TITLE
How to use CodyHouse with Nuxt?

### ISSUE THREAD

**Issue by slidenerd** [CodyHouse/codyhouse-framework#46]
- I searched for nuxt in the issues section and did not find anything
- the documentation also covers only gulp webpack and manual install
- how do I install CodyHouse base in nuxt
- Would be awesome if you can add a section in the guide for the same
- Fantastic work team, cheers

**Comment by claudia-romano** [comment]
Hi there! We do not have a doc section for nuxt yet. We're looking into it and see if we can add a new section soon.

Meanwhile, here's an article covering how to import the framework and components in Vue:
https://codyhouse.co/blog/post/using-the-codyhouse-components-with-vue-js

This should help you with nuxt as well. 
In the **Install the CodyHouse Framework** section, you can find how to import the base into your custom scss file. You can then compile the custom scss file in style.css as you would typically do using your nuxt.config.js file.

Hope this helps!

**Comment by HamzaPlus** [comment]
Hi Claudia!
First I would like to thank your team for the awesome framework, it made it to so easy to work!
I purchased a Pro version a week ago!
Now I'm looking for a documentation on how to integrated to a NuxtJS project!

**Comment by claudia-romano** [comment]
Hi Hamza, 
great to hear that! 

We didn't schedule a NuxtJS doc section yet. We do have an article on how to import the framework and components in Vue:
https://codyhouse.co/blog/post/using-the-codyhouse-components-with-vue-js

Are there any steps missing in that guide that you think we should cover? Thank you.

**Comment by retroriff** [comment]
@HamzaPlus, I am currently using CodyHouse CSS framework in a Nuxt.js project: https://www.acousticarium.com

However I am excluding the CH JS files because Vue is doing the task. It works fine but I am having [this issue](https://github.com/CodyHouse/codyhouse-framework/issues/80) purging the CSS.

**Comment by claudia-romano** [comment]
I'm closing this issues as everything seems to be working with PurgeCSS as well. Feel free to reopen it if there are still problems. Chers!

**Comment by heyharmon** [comment]
@slidenerd I've implemented CodyHouse with Nuxt. The trick is is making breakpoint.scss and mixins.scss a Nuxt resource. I recorded tutorials on this https://www.youtube.com/watch?v=ufMByFlIWck

@claudia-romano Feel free to share this video with anyone who needs it.

@retroriff Nice work on that website!

**Comment by claudia-romano** [comment]
Hi Ryan, thanks for that! We have included it in our Docs section:
https://codyhouse.co/ds/docs/framework#nuxt
