### ISSUE TITLE
Timeline doesn't expand if viewport is widenend.

### ISSUE THREAD

**Issue by sderrick** [CodyHouse/codyhouse-framework#47]
Open the Demo page with the timeline, with your browser narrowed down.  
press "Next" button until timeline shifted fully to the left. No more items to the right.
Then drag the page wider, the "Next" button shifts right but the timeline doesn't.  Pressing the "Next" button causes the timline to re-adjust to the wider view and look normal.

**Comment by sebastiano-guerriero** [comment]
Hi there! Please submit this issue to the Experiment/Component github repo. This repo is only for issues related to CodyFrame.

- On the experiments page, you'll find a link to download the source code on Github. You can submit the issue there.
- The components have a link to their Github repo on the "info page" of the component.
