### ISSUE TITLE
Strange Issue on Refresh (switching desktop / mobile views) - on certain components

### ISSUE THREAD

**Issue by DaveBeirne** [CodyHouse/codyhouse-framework#48]
Hi,

I have updated the code framework to codyhouse-framework@2.6.1 gulp
as i am having this strange issue where on all browsers even after flushing cache, and with no gulp sass or scripts errors, certain components i add to an existing projects on refresh show correctly then upon refreshing again it doesnt show correctly.

For example in this page i am using **masonry gallery** and see what happens:
**Video here**: https://drive.google.com/file/d/1D7x2njlYrNlLptT3xpBiPehPVN_ySoJl/view?usp=sharing

Another example when refreshing the page on the **mega-site-navigation**
When refreshing it switches between mobile version and dekstop
**Video Here**:  https://drive.google.com/file/d/16WMUGyVinhw3JT7f2ox9cH9q2C906woK/view?usp=sharing

its strange as there is no issues with other components

**Comment by claudia-romano** [comment]
Hi Dave, is this an issue you were experiencing before the upgrade as well?
The new version of the framework comes with some additional util classes and JS easing functions which should not affect those components.
I have beed testing it (mega site navigation on Chrome 80) and was not able to replicate the issue.

Could you please confirm you are including the JS file of the components right before the body closing tag?

Also, if you are including the CSS using the [<script> to switch between style.css and style-fallback.css](https://codyhouse.co/ds/docs/framework#gulp), could you try with a direct import and see if anything changes? Thanks
```<link rel="stylesheet" href="assets/css/style.css">```

From your video it looks like you are using a page transition plugin; does the bug persist if you turn that plugin off? Thanks.

**Comment by DaveBeirne** [comment]
Hi Claudia,

Just using this seems to remove the probelm:

`  <script>document.getElementsByTagName("html")[0].className += " js";</script>
  <link rel="stylesheet" href="assets/css/style.css">
  <noscript>
    <link rel="stylesheet" href="assets/css/style-fallback.css">
  </noscript>`


This is my JS setup just before the body closing tag:

<img width="697" alt="Screenshot 2020-04-16 at 11 14 57" src="https://user-images.githubusercontent.com/1081103/79444837-9e5ddd00-7fd3-11ea-9ce3-e7d60146ab58.png">

**Comment by claudia-romano** [comment]
Hi Dave,
if you are not supporting IE, you won't have any issues.

If you need to support IE, please try the following code:
```
<script>document.getElementsByTagName("html")[0].className += " js";</script>
<link id="codyframe-css" rel="stylesheet" href="{{ siteUrl }}assets/css/style.css">
<!-- IE11 support -->
<script>
    if(!('CSS' in window) || !CSS.supports('color', 'var(--color-var)')) {var cfStyle = document.getElementById('codyframe-css');if(cfStyle) {var href = cfStyle.getAttribute('href');href = href.replace('style.css', 'style-fallback.css');cfStyle.setAttribute('href', href);}}
</script>
```
Let me know if you are still having problems. Thanks.

**Comment by DaveBeirne** [comment]
I have been through the War of IE6 and still get flashbacks ha ha

Thank you for all your help and great work!
