### ISSUE TITLE
Input Merge - Firefox Bug

### ISSUE THREAD

**Issue by bacounts** [CodyHouse/codyhouse-framework#49]
There seems to be a bug for the Input Merge component in Firefox. The text boxes stack by default. Please see the screenshot below. The component works fine in Chrome and Safari.

<img width="1058" alt="Screen Shot 2020-05-05 at 4 21 30 PM" src="https://user-images.githubusercontent.com/6481954/81125299-99ae8980-8eec-11ea-819a-0d366c2f81bd.png">

**Comment by claudia-romano** [comment]
Hi Bryan, thanks for the heads-up. It should be fixed now. Cheers!
