### ISSUE TITLE
[ERROR] Feature v4 Component HTML

### ISSUE THREAD

**Issue by bacounts** [CodyHouse/codyhouse-framework#50]
Feature v4 Component - There is a random </svg> close tag without an opening. This is creating an HTML error - see the screenshot below.

<img width="1056" alt="Screen Shot 2020-05-07 at 9 51 44 PM" src="https://user-images.githubusercontent.com/6481954/81371544-01133780-90ad-11ea-9a7c-29b5e7600064.png">

**Comment by sebastiano-guerriero** [comment]
Thanks for the heads up! We'll push an update soon.

For more feedback/bug reports about this component or others, please submit them to the components' changelog repos: https://github.com/CodyHouse/cd-feature-v4-changelog
