### ISSUE TITLE
It would be better combine with handlebars.js 

### ISSUE THREAD

**Issue by tinybug** [CodyHouse/codyhouse-framework#52]
codyhouse framework is really great framework for static website ~

But it would be better combine with handlebars.js for html components. 
For example, the header component can just write once and then use in multi pages.

Will you consider this plan？

**Comment by tinybug** [comment]
This https://github.com/tinybug/codyhouse-framework/commit/b33ade66fbcd4fe0ed3e01160c3d8330bb9a8aae is what I changed, please check it out. simpily run:
```bash
# install package
yarn 

# for dev
yarn start

# for build
yarn build
```

**Comment by sebastiano-guerriero** [comment]
Hi there! That's a good point! I agree that providing a version of the components that is more "component-friendly" in terms of reusability would be beneficial to all our users. I'm not sure handlebar.js would be the best solution though. At the moment, we're experimenting with native web components, that come with many advantages (they're native; they should work fine with libraries like Vue/React.js). We'll keep looking into this 👍

**Comment by tinybug** [comment]
handlebar.js can be written in vanilla html，it's easier than Vue/React.js for those people who don't know a lot develop tech and I think handlebar.js is more suitable for static website.

**Comment by sebastiano-guerriero** [comment]
That's definitely an option we'll consider. Before committing to a decision that means for us updating hundreds of components, we'll get in touch with the community (e.g., a poll), and see what the majority prefers. Cheers

**Comment by sanzwebdevelopment** [comment]
Not sure about handlebars.js however I'm currently looking at whether it might be useful to build each component with [Stencil](https://stenciljs.com/). I currently use Ionic (the Angular flavour) which uses Stencil for it's components.

Just a thought :-)

**Comment by sebastiano-guerriero** [comment]
We will never remove the vanilla HTML, CSS, JS versions :) I agree that they're great for building static websites, and they work seamlessly with termplating languages like handlebar.js. If we integrate a new version of the components (react, vue, stencil or native web components), it will be an additional version, not a replacement of the current components.

**Comment by sebastiano-guerriero** [comment]
I'm closing this issue because we've gathered some interesting info, but I don't think we can add more to this conversation. Thanks for the feedback!
