### ISSUE TITLE
max-width-adaptive-lg can't use break point

### ISSUE THREAD

**Issue by tinybug** [CodyHouse/codyhouse-framework#57]
why max-width-adaptive-lg@lg is till work in mobile size ?

**Comment by sebastiano-guerriero** [comment]
the max-width classes (including the max-width-adaptive classes) don't have responsive helpers, therefore the max-width-adaptive-lg@lg class does not exist:

https://codyhouse.co/ds/docs/framework/utilities#max-width

**Comment by tinybug** [comment]
will it support in the future?

**Comment by sebastiano-guerriero** [comment]
I haven't found a use case where the max-width classes would benefit from responsive modifiers. Can you please describe your use case so I can look into it (even better if you have a live example)?

**Comment by tinybug** [comment]
in the below image, I don't want the margin in the mobile, so container@lg and max-width-xl@lg is the case I want

![1591972872651](https://user-images.githubusercontent.com/3439875/84514625-e82a2180-acfd-11ea-89dd-b9facd5a57d6.jpg)

**Comment by sebastiano-guerriero** [comment]
you can achieve this by using other utility classes:

```html
<div class="max-width-adaptive-md margin-x-auto padding-x@lg"></div>
```

**Comment by tinybug** [comment]
thanks sebastiano~

**Comment by sebastiano-guerriero** [comment]
no prob 👍
