### ISSUE TITLE
will framework support style elements on hover, focus, and more ?

### ISSUE THREAD

**Issue by tinybug** [CodyHouse/codyhouse-framework#59]
taildwind.css support pseudo-Class variants, it can write class name like: hover:border-gray-300 focus:outline-none focus:bg-white...

will codyhouse support this feature in the future?

**Comment by sebastiano-guerriero** [comment]
Hi there! We don't plan on adding pseudo-class variants, but we're working on a method that tackles the same use case. It will be revealed over the next few weeks (it's going to be a new global editor).

**Comment by tinybug** [comment]
ok, thanks~
