### ISSUE TITLE
issues with gulp watch

### ISSUE THREAD

**Issue by starchild** [CodyHouse/codyhouse-framework#6]
I'm trying really hard to get this gulp thing working, but just can't seem to do it.

I think you'll have a better take up if this initial part of the set up is made a bit clearer.

- when I run 'npm run gulp watch' from the  'my_project/node_modules/codyhouse-framework' path, 
 I get a whole bunch of errors, despite having followed the instructions on https://css-tricks.com/gulp-for-beginners/

have I run it from the wrong path maybe?

node --version
v10.15.0

gulp -v
[16:47:04] CLI version 2.0.1
[16:47:04] Local version 4.0.0

**Comment by dfpera** [comment]
Did you run `npm install` before running `npm run gulp watch`?

That's the first thing that comes to mind when you say you are getting a lot of errors. That is because you need to "install" the packages before you can use them, one of those packages being "gulp".

**Comment by starchild** [comment]
yes i did:

npm install gulp-sass --save-dev
npm install
npm run gulp watch

Can you confirm if I have missed anything?
Can you also please confirm what path these should be run from?

Thanks!

**Comment by starchild** [comment]
yes, ok great - I;ve worked this out now.... and it seems to be working, but now generating the following error, which has to do with what I followed in the demo youtube video for the _table.scss

[17:08:20] Starting 'sass'...
Error in plugin "sass"
Message:
    main/assets/css/_components.scss
Error: File to import not found or unreadable: table.
        on line 2 of main/assets/css/_components.scss
        from line 2 of main/assets/css/style.scss
>> @import 'table';
   ^

[17:08:20] Finished 'sass' after 15 ms

**Comment by starchild** [comment]
edit: i fixed it! . my _components.scss had:

@import 'table';

instead of:

@import 'components/table';

Thank you for your help :)

**Comment by dfpera** [comment]
Awesome glad to hear. Guess we can close this issue.
