### ISSUE TITLE
Why not use css instead of scss as you suggested in your blog article?

### ISSUE THREAD

**Issue by youssefsharief** [CodyHouse/codyhouse-framework#64]
Why not use css instead of scss as you suggested in your blog article?

**Comment by youssefsharief** [comment]
I mean this [article](https://codyhouse.co/blog/post/css-custom-properties-vs-sass-variables). I was wrong when I said you suggested using CSS rather than scss, but one of the main reasons we use scss is variables.

**Comment by sebastiano-guerriero** [comment]
Hi there! While we use CSS variables for most of the CodyFrame customizations (including the customization of the components), we need to rely on SCSS for some functionalities that can't be powered by CSS-only at the moment. 

For example:
- Breakpoints - it's not possible to use CSS variables for defining the breakpoints
- Loops - SCSS allows you to create loops (e.g., for the grid and utility classes, based on the number of breakpoints set by the user)
- [Color functions](https://codyhouse.co/blog/post/how-to-combine-sass-color-functions-and-css-variables)
- Nesting - The possibility of nesting CSS makes it easier to read it (and write it) IMO

**Comment by youssefsharief** [comment]
Thank you so much for your insights
