### ISSUE TITLE
How to use CodyHouse with Gatsby? 

### ISSUE THREAD

**Issue by ThongKun** [CodyHouse/codyhouse-framework#67]
I followed this guide but I still cannot make it work.
https://codyhouse.co/blog/post/using-the-codyhouse-components-with-react
Really Grateful!

**Comment by claudia-romano** [comment]
Hi there,
could you please provide more info about the problem you are experiencing? Thanks.

**Comment by peiche** [comment]
Hi, I maintain two different websites with Gatsby and CodyFrame. They're closed-source, so I can't link directly to them, but if you can provide some code, I can probably point you in the right direction.

**Comment by ThongKun** [comment]
Thank you guys, I resolved it.
