### ISSUE TITLE
Using gulp with PHP files

### ISSUE THREAD

**Issue by w3work** [CodyHouse/codyhouse-framework#69]
Hi CodyHouse-Team,

i want to use gulp with PHP files, but i dont find any solution for this with the current gulp version 4.
There are some threads on stackoverflow, but i don't get any working watcher with this.

In previous projects we helped use with switching back to gulp version 3.9. Here it was possible to use "gulp-connect-php".
But with this new and entangled gulpfile.js and purgeCSS there is no way back to gulp 3.9.

So is there a way you can provide a optional gulpfile.js, where it is possible to use PHP files?

Regards
Sven

**Comment by claudia-romano** [comment]
Hi Sven,
the purgeCSS option has not been added to the default `watch` task but it has been included in a separate `dist` task, as you can see from the gulp.js file here:
https://gist.github.com/claudia-romano/523c46f02cee8035f6d9900d09bda292

As the `watch` task has not been modified, you can keep using the version you already had; the `watch` task is the only one you would need to use with a plugin like gulp-connect-php for the live page refresh. If you wish to use the `dist` task, you won't need any live reload.

Cheers!

**Comment by w3work** [comment]
Nice to see, that you also use a gulp version for PHP files. :)
Thank you for this input, i will have a look into it. 👍 

Cheers!
