### ISSUE TITLE
Error when compiling SCSS

### ISSUE THREAD

**Issue by erodr015** [CodyHouse/codyhouse-framework#70]
Platform: Hubspot CMS

I've used both terminal and an online conversion tool. 

- [Error One](https://content.screencast.com/users/Erodr015/folders/Capture/media/1880b07a-40d9-4650-9a93-bcce4894a496/screenshot.png)
- [Error Two](https://www.screencast.com/t/9WZCDIpg)

Not sure where $breakpoint is defined.

**Comment by sebastiano-guerriero** [comment]
Hi! I've never used the Hubspot CMS so I'm not sure how it works. From the errors, it appears you're not loading the base SCSS files (the files in the /css/base/* folder).  For example, the mixins are defined in the css/base/_mixins.scss file.

**Comment by erodr015** [comment]
Hi Sebastiano, hubspot can be a little picky. I was able to resolve the css issue by doing what you suggested but now I'm running into a different issue. 

When I click the sliding panels nothing happen and I get this: https://www.screencast.com/t/ZbzUFcINWnNL

This is the order of the files: https://www.screencast.com/t/cMqfht5AigkD

Not sure if you have access but [this is the staging](https://preview.hs-sites.com/_hcms/preview/template/multi?domain=undefined&hs_preview_key=iEj4n_K5RXyAPs6CviY14Q&portalId=6738295&tc_deviceCategory=undefined&template_file_path=Dissect_Podcast/Dissect_Landing_Page/pages/index.html&updated=1608321894638)

Thank you!

**Comment by sebastiano-guerriero** [comment]
Hi! For component related questions, please open an issue on the component's github page. You'll find the link on the 'info page' of each component.

The Sliding Panel component may need to be initialized. More info here: https://codyhouse.co/ds/components/info/sliding-panels

Cheers

**Comment by erodr015** [comment]
Thank you sebastiano. I want to make sure we're on the same page before I jump to another section. The sliding panel by itself works great. The sliding panel that's part of the Giove template does not. It's definitely a JS issue. Is this still a component issue or is there a place for template issue? Cheers, Edgar

**Comment by sebastiano-guerriero** [comment]
Hi Edgar! Please submit it to the Giove github page: https://github.com/CodyHouse/cd-giove-changelog

Cheers
