### ISSUE TITLE
Suggestion for more integration with ES6

### ISSUE THREAD

**Issue by MasionGIT** [CodyHouse/codyhouse-framework#72]
Hi, I think adapting your gulpfile.js like I have done in the files attached will be better for more use cases as my of us particularly me use alot of ES6 syntax and operators and working with older version of JS for the components is harder. I have attached files on my gulpfile.js which will show you what to do that enables ES6 compiling. (Ignore the nodemon section that is just a custom thing). Thanks :) (Let me know if you need any help working with gulp I know the compiling is great but they havent expanded the tool very well with JS ;) )

![Screenshot 2021-01-09 at 01 56 33](https://user-images.githubusercontent.com/59147501/104089531-283f8b80-5270-11eb-9672-18004076fca7.png)
![Screenshot 2021-01-09 at 01 56 46](https://user-images.githubusercontent.com/59147501/104089532-2a094f00-5270-11eb-838a-8f45cff42a6a.png)
![Screenshot 2021-01-09 at 01 56 22](https://user-images.githubusercontent.com/59147501/104089533-2aa1e580-5270-11eb-89a5-06bfa67c0247.png)
![Screenshot 2021-01-09 at 01 56 54](https://user-images.githubusercontent.com/59147501/104089534-2b3a7c00-5270-11eb-9789-4d7f70354375.png)

**Comment by JonQuayle** [comment]
@MasionGIT Are you able to provide any more info on how you are integrating es6? For me the util.js file can't be read whenever the js is bundled up which makes the components pretty useless.

**Comment by claudia-romano** [comment]
@JonQuayle Hi there, this is a closed issue. 
You can use the open discussion if you want to share more info about this topic:
https://github.com/CodyHouse/codyhouse-framework/discussions/75

Cheers!
