### ISSUE TITLE
Width classes are not responsive

### ISSUE THREAD

**Issue by emilycritter** [CodyHouse/codyhouse-framework#78]
https://codyhouse.co/ds/docs/framework/util-width#responsive
![image](https://user-images.githubusercontent.com/16456162/106060954-53243f00-60ba-11eb-8d17-5c04c3e242bf.png)

Classes such as `width-auto@md` have no associated css. Is this intentional? The documentation (included above) makes it sound like the responsive variations of "width" classes are available.

**Comment by sebastiano-guerriero** [comment]
Hi Emily, you should look for `width-auto\@md` in the CSS file. Special characters such as '@' require '\' when used in CSS. The responsive classes are working fine, here's an example that imports the CSS from the repo:
https://codepen.io/codyhouse/pen/YzpKENV?editors=1100

**Comment by emilycritter** [comment]
Looks like we were using an old export of the base/ css files. Thank you!
