### ISSUE TITLE
Flexi Header - fixes for non-JS representation

### ISSUE THREAD

**Issue by oppenheimer-** [CodyHouse/codyhouse-framework#82]
When JS is turned off, the navigation does not push the content below it. Here are fixes that worked for me.
```sass
html:not(.js)
    .f-header
        height: auto
    .f-header__nav
        max-height: unset
        height: auto
        padding: var(--space-xxs) 0
    &:before
        content: unset
    .f-header__mobile-content
        height: var(--f-header-height)
```

**Comment by claudia-romano** [comment]
Hi there,
thanks for the heads-up. We have pushed an updated version of the component fixing this issue:
https://codyhouse.co/ds/components/app/flexi-header

If you have additional issues with the Flexi header (or any other CodyHouse components), you can open an issue on the component GitHub page. You can find the link at the bottom of each component Info page: 
https://codyhouse.co/ds/components/info/flexi-header

This way we can keep this for issues with CodyFrame only. Thanks!
