### ISSUE TITLE
Gulp watch localhost:3000 does not work

### ISSUE THREAD

**Issue by klarplan** [CodyHouse/codyhouse-framework#84]
I use Codyframe with Craft CMS on Nitro 2 based on Docker. Gulp watch calls localhost:3000 but I get a 404. Any idea why? Thanks

**Comment by claudia-romano** [comment]
Hi there,
the gulp file opens the default index.html file. Is this file missing in your project? 

Cheers!

**Comment by klarplan** [comment]
I may have found the cause. Nitro 2 does not allow access via port 3000 at the moment, but that should be possible in the next version. I test it then.
