### ISSUE TITLE
Open "Drawer" via freshly created items don't work

### ISSUE THREAD

**Issue by addwot** [CodyHouse/codyhouse-framework#86]
**When I add new items with JS those have to open Drawer/Modal, they aren't able to do so.**

Worked perfectly for Lazyload component with
new LazyLoad(document.querySelectorAll('[loading="lazy"]'));

but for Drawer, it doesn't work, got "Drawer is not defined"

**Comment by claudia-romano** [comment]
Please use this for framework related bugs only. Each component has its own repository that you can use. Thanks.
