### ISSUE TITLE
Variable X is undefined and used without a fallback

### ISSUE THREAD

**Issue by madsfors** [CodyHouse/codyhouse-framework#88]
When using the gulp script "npm run gulp watch-ie" I get following postcss-css-variables error:

<img width="882" alt="CleanShot 2021-05-12 at 11 03 32@2x" src="https://user-images.githubusercontent.com/2444115/117948755-bbb5c580-b311-11eb-960b-0e6484c3c28e.png">

The variables are from the TOC component and haven't been altered in any way.

**Comment by iKeule257** [comment]
Same here.
Happens even on a completely fresh download of the codyhouse-framework-master.zip when running the sass-ie task.
![screenshot](https://user-images.githubusercontent.com/49203720/117975495-05f96f80-b32f-11eb-9982-a2a96876e197.PNG)

**Comment by sebastiano-guerriero** [comment]
Hi 👋 It's an issue with the postcss-css-variables plugin: if the variables are not defined in the :root, it throws a warning. The variables are defined and work fine (e.g., the --gap-x variable is defined in the .grid class).

**Comment by madsfors** [comment]
Hi Sebastiano. Thanks for the reply! The variables work as expected (and thus works 👌 in any modern browser), but whenever using the generated style-fallback.css, the styling seems to break. I'm in the (unfortunate) situation that I have to support IE11 so I'm experiencing code that turns out with "undefined" declarations. This is i.e. happening with the lists component. See below:

<img width="409" alt="CleanShot 2021-05-13 at 13 21 31@2x" src="https://user-images.githubusercontent.com/2444115/118119308-74513700-b3ee-11eb-803b-597193912ae9.png">
<img width="400" alt="CleanShot 2021-05-13 at 13 22 15@2x" src="https://user-images.githubusercontent.com/2444115/118119311-75826400-b3ee-11eb-9971-1deb13526128.png">

How would you suggest fixing this issue?

**Comment by sebastiano-guerriero** [comment]
Hi! Moving the custom properties to the :root element should fix the issue:

```scss
:root {
  --list-space-y: var(--space-xxs); // vertical gaps
  --list-offset: var(--space-xs);  // sublist horizontal offset
  --list-line-height: var(--body-line-height);  // items line-height
}
```

I'll give it a test 👍

**Comment by madsfors** [comment]
It's not really fixing it, unfortunately. The error is gone but the output is not satisfactory:
<img width="847" alt="CleanShot 2021-05-17 at 10 08 33@2x" src="https://user-images.githubusercontent.com/2444115/118453891-02cbfe00-b6f8-11eb-9899-8239ab5b3a12.png">

**Comment by sebastiano-guerriero** [comment]
We just published a new version of the List component that fixes the IE issues:
https://codyhouse.co/ds/components/app/list

**Comment by madsfors** [comment]
Perfect. Thanks a lot!
