### ISSUE TITLE
The sass-ie gulp task produces a faulty style-fallback.css when using the Auto Sized Grid component

### ISSUE THREAD

**Issue by iKeule257** [CodyHouse/codyhouse-framework#89]
No other component was added, just the Auto Sized Grid.

![screenshot](https://user-images.githubusercontent.com/49203720/117962828-f0c91480-b31f-11eb-8528-895541d2922d.PNG)

**Comment by claudia-romano** [comment]
Hi there,
it looks like there's an issue when converting the following line of code to CSS:
```css
gap: var(--gap-y, 0) var(--gap-x, 0);
```

You can replace that line with:
```css
row-gap: var(--gap-y, 0);
column-gap: var(--gap-x, 0);
```
We'll update the component as soon as possible.

Cheers!
