### ISSUE TITLE
Color missing from transition property dropdown in button globals editor

### ISSUE THREAD

**Issue by danis039** [CodyHouse/codyhouse-framework#92]
Hi guys,

Any possibility of adding "color" to the transition property dropdown in button globals editor? I personally use it quite a lot and currently the alternative is either using "all" - which I'd rather avoid - or manually editing the code.

<img width="275" alt="Screenshot 2021-05-19 at 08 44 12" src="https://user-images.githubusercontent.com/11977521/118768158-f920d280-b87e-11eb-8475-f66538ce1d3b.png">

Thanks and keep up the amazing work!

**Comment by sebastiano-guerriero** [comment]
Hi Daniel! Sure, we're on it ;)

**Comment by claudia-romano** [comment]
Hi Daniel, just added it!
https://codyhouse.co/ds/globals/buttons

Cheers!

**Comment by danis039** [comment]
> Hi Daniel, just added it!
> https://codyhouse.co/ds/globals/buttons
> 
> Cheers!

You rock!! Thanks once again!! :)
