### ISSUE TITLE
Warning for Sass 2.0.0

### ISSUE THREAD

**Issue by YannickMol** [CodyHouse/codyhouse-framework#94]
I am getting the following warning for some of the elements in the framework:

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

node_modules\codyhouse-framework\main\assets\css\base\_mixins.scss 139:18       round-width()
node_modules\codyhouse-framework\main\assets\css\base\_grid-layout.scss 130:27  @import
node_modules\codyhouse-framework\main\assets\css\_base.scss 13:9                @import
```

Are you aware of this warning and will this be fixed in upcoming release?

Thanks!

**Comment by sebastiano-guerriero** [comment]
Hi! We will update soon to the new SASS modules system 👍 We're figuring out how to do so without creating issues for users who are not using SASS 2.0

**Comment by patrickedqvist** [comment]
A lot of packages are installing dart-sass per default and it's quite easy to get the information that node-sass is deprecated. Maybe create a new major version with breaking changes and keep the current version with some short-term support?

I would love to see the new dart sass version implemented 🤗

**Comment by sebastiano-guerriero** [comment]
We're running the first tests using dart SASS in CodyFrame. The main issue we've run into: the dart-sass compiler is 2-3x slower compared to the node-sass compiler. It appears the SASS team is working on a potential solution, even though it's not clear when it will be available and what impact it will have on the performance.

More info here: https://github.com/sass/dart-sass/issues/113

Have you experienced the same issue?

**Comment by patrickedqvist** [comment]
@sebastiano-guerriero I have only read about it when different frameworks have mentioned that you can use either node-sass and dart-sass with dart-sass being slower. That said, the longer compile time hasn't been causing any frustration in any of our projects which range from small to medium-sized projects.

**Comment by sebastiano-guerriero** [comment]
@patrickedqvist good to know! 👍 

Btw, the SASS team is working on a new package where the compiler is faster: https://www.npmjs.com/package/sass-embedded

**Comment by retroriff** [comment]
I am receiving lots of warnings, while I am supposed to be using `node-sass` instead of `dart-sass`. May be `sass-loader` who is triggering those messages?

**Comment by claudia-romano** [comment]
We just release CodyFrame 3.0 that supports Sass Modules:
https://codyhouse.co/blog/post/codyframe-3-0

We are still supporting CodyFrame v2 for node-sass users:
https://github.com/CodyHouse/codyhouse-framework/tree/v2

Cheers!
