### ISSUE TITLE
Error: Undefined mixin.

### ISSUE THREAD

**Issue by dariopetraroia** [CodyHouse/codyhouse-framework#98]
I have this error after npm run gulp watch, using CodyFrame 3.0
I thought it was an update problem but it also gives it with a fresh installation.

```
Error in plugin "sass"
Message:
    main\assets\css\custom-style\_colors.scss
Error: Undefined mixin.
  ╷
9 │   @include defineColorHSL(--color-primary-darker, 210, 100%, 0%);
  │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  main\assets\css\custom-style\_colors.scss 9:3  @use
  main\assets\css\_custom-style.scss 7:1         @use
  main\assets\css\style.scss 13:1                root stylesheet
```

**Comment by sebastiano-guerriero** [comment]
Hi Dario, have you downloaded CodyFrame 3 from our website or from Github? Are you using our Gulp configuration file?

**Comment by dariopetraroia** [comment]
Hy Sebastiano, I use the export section on the codyhouse website: https://codyhouse.co/ds/export

Yes I use your gulp config file

**Comment by claudia-romano** [comment]
Hi Dario, thanks for the additional info. There was a bug with the Export feature. We just pushed an update to fix that. 

I'm closing this but feel free to reopen it if you are still having issues. Thanks!

**Comment by dariopetraroia** [comment]
Hy Claudia, now I have an error with npm install, in package.json with "sass-embedded": "^1.0.0-beta.3"

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sass-embedded@1.0.0-beta.3 postinstall: `node ./download-compiler-for-end-user.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sass-embedded@1.0.0-beta.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by claudia-romano** [comment]
Hi Dario, the change we did was to fix the export of the globals (a '@use base.scss' was misssing from the _colors.scss file). Were you able to install the modules when you first opened the issue? Thanks

**Comment by dariopetraroia** [comment]
I think so but now I am having the problem also bu installing only the sass-embedded package, it seems that this problem was already known in the version prior to beta3

https://github.com/sass/embedded-host-node/releases/tag/1.0.0-beta.1

I will try to make a few more attempts

**Comment by dariopetraroia** [comment]
Hy Claudia, changing "sass-embedded": "^1.0.0-beta.3" to "sass-embedded": "1.0.0-beta.3" fixed the problem.

Thank you ;)
